name: world

on:
  push:
    tags:
      - "world@*.*.*"
  workflow_call:
    inputs:
      is_root:
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Build world
        run: |
          cd world
          ./build.sh
      - name: Release world if this action is not called by root.yml
        if: inputs.is_root == false
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: world/world.txt
          asset_name: world.txt
          tag: ${{ github.ref }}
      - name: Upload artifact if this action is called by root.yml
        if: inputs.is_root == true
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: world/world.txt
